### ISSUE TITLE
trap-failure/failure.sh: line 24: local: -n: invalid option / line 25: local: -n: invalid option

### ISSUE THREAD

**Issue by tekvax** [bash-utilities/trap-failure#2] opened 2020-05-06 01:16 UTC
**Describe the bug**
I keep getting the following errors, when running the example code.
trap-failure/failure.sh: line 24: local: -n: invalid option
local: usage: local [option] name[=value] ...
/usr/local/bin/trap-failure-example/modules/trap-failure/failure.sh: line 25: local: -n: invalid option
local: usage: local [option] name[=value] ...

Here is the version of BASH I'm using from RHEL 7.7
[root@ftpdb02 trap-failure-example]# bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Here is the version of RHEL
[root@ftpdb02 trap-failure-example]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.7 (Maipo)
[root@ftpdb02 trap-failure-example]# uname -a
Linux ftpdb02.bell.corp.bce.ca 3.10.0-1062.9.1.el7.x86_64 #1 SMP Mon Dec 2 08:31:54 EST 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@ftpdb02 trap-failure-example]#

I ran it exactly as it was presented. below is the exact console output.
Any idea's as to why it's having the local -n invalid option errors?

[root@ftpdb02 trap-failure-example]# bash example_usage.sh
something_functional: spam ham example_usage.sh: line 42: /usr/local/bin/trap-failure-example/nothing.sh: No such file or directory
Ignored something_functional returning 127
example_usage.sh: line 42: /usr/local/bin/trap-failure-example/nothing.sh: No such file or directory
### Testing Failure Trap ###
something_functional: spam SPAM example_usage.sh: line 42: /usr/local/bin/rssctv_long/trap-failure-example/nothing.sh: No such file or directory
/usr/local/bin/trap-failure-example/modules/trap-failure/failure.sh: line 24: local: -n: invalid option
local: usage: local [option] name[=value] ...
/usr/local/bin/trap-failure-example/modules/trap-failure/failure.sh: line 25: local: -n: invalid option
local: usage: local [option] name[=value] ...
---
lines_history: [ ]
function_trace: [failure something_functional main]
exit_code: 127
source_trace:
  - /usr/local/bin/trap-failure-example/modules/trap-failure/failure.sh
  - example_usage.sh
  - example_usage.sh
last_command: "${__DIR__}/nothing.sh"
---
[root@ftpdb02 trap-failure-example]#

Thanks for your assistance.
Cheers,
Dan Braun

**Comment by S0AndS0** [comment] 2020-05-06 18:41
Thanks for reporting this bug in such detail!


```
trap-failure/failure.sh: line 24: local: -n: invalid option
trap-failure/failure.sh: line 25: local: -n: invalid option
```


... errors are unfortunate as that indicates that the device doesn't have the ability to pass arrays by name (reference). After a bit of searching it seems that Bash version `4.3` is where the `-n` option was introduced; I'll be sure to update the ReadMe file with that.


Reviewing the bug report shows that your device is barely under the required version to make use of `-n` option of the `local` shell built-in, and I believe that updating Bash to a version `4.3` or greater _should_ resolve this.


However, upgrading is not necessarily required to make partial use of the `failure` function, because the `-n` option is used for obtaining line numbers leading up to and generating errors, and only builds the `lines_history` portion of error reports...


**`failure.sh` snip(s)**


```bash
failure(){
  local -n _lineno="${1:-LINENO}"
  local -n _bash_lineno="${2:-BASH_LINENO}"
  # ...
  _output_array+=(
      '---'
      "lines_history: [${_lineno} ${_bash_lineno[*]}]"
      "function_trace: [${FUNCNAME[*]}]"
      "exit_code: ${_code}"
  )
  # ...
}
```


**Error report **with** `local -n` support**


```
---
lines_history: [42 42 53 0]
function_trace: [failure something_functional main]
exit_code: 127
source_trace:
  - ${HOME}/bash-utilities/trap-failure/modules/trap-failure/failure.sh
  - example_usage.sh
  - example_usage.sh
last_command: "${__DIR__}/nothing.sh"
---
```


**Error report **without** `local -n` support**


```
---
lines_history: []
function_trace: [failure something_functional main]
exit_code: 127
source_trace:
  - ${HOME}/bash-utilities/trap-failure/modules/trap-failure/failure.sh
  - example_usage.sh
  - example_usage.sh
last_command: "${__DIR__}/nothing.sh"
---
```


... in other-words the `local` built-in supporting `-n` is optional if ya don't mind missing out on `lines_history`


------


The other error...


```
something_functional: spam SPAM example_usage.sh: line 42: /usr/local/bin/rssctv_long/trap-failure-example/nothing.sh: No such file or directory
```


... is expected/intended behavior to show what the `failure` function outputs. The following blocks dive into the interactions between `example_usage.sh` and `failure.sh` in more detail...


```
something_functional: spam ham example_usage.sh: line 42: ${HOME}/git/hub/bash-utilities/trap-failure/nothing.sh: No such file or directory
```


```
#> example_usage.sh
#> #46: something_functional 'spam' 'ham' || echo "Ignored something_functional returning $?"
Ignored something_functional returning 127
```


> Note, above outputs the `echo` message because logical OR (`||`) _consumes_ errors code(s) generated by `something_functional` call


```
#> example_usage.sh
#> #48: if [[ "$(something_functional 'spam')" == '0' ]]; then
#> #49:    printf 'Nothing somehow was something?!\n' >&2 && exit 1
#> #50 fi
```


> Note, above doesn't output anything because the errors codes from `something_functional` call are _consumed_ within `if` blocks
>
> For both `||` and `if` checks this is how Bash can _catch_ error states


```
#> example_usage.sh
#> #52: echo "### Testing Failure Trap ###"
### Testing Failure Trap ###
```


```
#> #53: something_functional 'spam'
#> Default error output
something_functional: spam SPAM example_usage.sh: line 42: ${HOME}/git/hub/bash-utilities/trap-failure/nothing.sh: No such file or directory
```


```
#> `failure` function output
---
lines_history: [42 42 53 0]
function_trace: [failure something_functional main]
exit_code: 127
source_trace:
  - ${HOME}/git/hub/bash-utilities/trap-failure/modules/trap-failure/failure.sh
  - example_usage.sh
  - example_usage.sh
last_command: "${__DIR__}/nothing.sh"
---
```



## Attribution


- [How to pass array as an argument to a function in Bash](https://stackoverflow.com/a/26443029)

- [Variable definition in bash using the local keyword](https://unix.stackexchange.com/questions/202302/)

- [local: -n: invalid option](https://stackoverflow.com/questions/40237782/)

**Comment by tekvax** [comment] 2020-05-06 23:10
Thank you for responding so quickly!
I ended up installing a local version of bash, because I didn't want to
remove the native RHEL version, and possibly mess with the RHEL yum update
database tools.

I realised the second error was by design but included it in the report as
it was part of the designed demo run script.

Cheers,
dan
--
Dan Braun (dan @ tekvax . com )
Broadcast Engineering
Burlington, Ontario, Canada

**Comment by S0AndS0** [comment] 2020-05-07 05:09
You're very welcome. And feel free to open an Issue like this again if something fails strangely.

That seems prudent. I've not yet had to explore that route so if ya wish to open a Pull Request with any special instructions, I'd be happy to merge in documentation for installing multiple versions of Bash without trampling the distribution's defaults.

Excellent choice, I wasn't about to assume that nor that any future readers would know it's intended output from the test script either.

------

As this Issue seems to be resolved I'll be closing it, but it's totally okay for anyone reading this comment to re-open this Issue if there's something that has been missed.

**Closed as completed by S0AndS0** 2020-05-07 05:09 UTC
